# Data Cleaning

### 1. Import thư viện pandas và load dataset

In [1]:
import pandas as pd

data = pd.read_csv("../data/raw/data-raw.csv")

display(data)

,observation_id,timestamp,session_id,location_id,time_of_day,signal_mean,signal_std,rx_link_rate_mean,tx_link_rate_mean,rtt_mean_ms,rtt_std_ms,jitter_ms,packet_loss_pct,throughput_down_mbps
0,O001,2026-09-05T16:15:15,D5_1_AFTERNOON,1,afternoon,79.416667,0.514929,866.7,866.700000,1.100000,0.316228,0.222222,0.0,94.402610
1,O002,2026-09-05T16:15:36,D5_1_AFTERNOON,1,afternoon,80.000000,0.000000,866.7,866.700000,1.800000,2.529822,0.888889,0.0,94.365150
2,O003,2026-09-05T16:15:57,D5_1_AFTERNOON,1,afternoon,80.000000,0.000000,866.7,866.700000,2.666667,4.636809,1.750000,10.0,94.672873
3,O004,2026-09-05T16:16:23,D5_1_AFTERNOON,1,afternoon,80.000000,0.000000,866.7,866.700000,1.555556,1.333333,1.125000,10.0,93.968420
4,O005,2026-09-05T16:16:48,D5_1_AFTERNOON,1,afternoon,81.000000,0.000000,866.7,866.700000,3.800000,4.732864,4.222222,0.0,94.647882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,O026,2026-09-07T09:20:08,D7_3_MORNING,2,morning,34.750000,1.544786,1.0,6.500000,459.900000,542.296649,450.777778,0.0,0.104711
356,O027,2026-09-07T09:20:45,D7_3_MORNING,2,morning,34.000000,1.477098,1.0,7.041667,576.700000,358.224960,375.111111,0.0,0.000000
357,O028,2026-09-07T09:21:11,D7_3_MORNING,2,morning,34.000000,1.477098,1.0,6.500000,485.700000,481.156258,464.888889,0.0,0.104701
358,O029,2026-09-07T09:21:41,D7_3_MORNING,2,morning,33.500000,2.504541,1.0,7.583333,192.400000,173.633202,253.444444,0.0,0.000000
359,O030,2026-09-07T09:22:10,D7_3_MORNING,2,morning,33.250000,0.866025,1.0,6.500000,340.100000,256.879327,287.555556,0.0,0.000000

### 2. Bỏ các cột `observation_id`, `session_id` và `time_of_day`

Lý do: Không sử dụng `observation_id` và `session_id` trong EDA hay các bước học máy sau. Trong khi đó `time_of_day` lại tính toán từ `timestamp` (Chương 3 báo cáo)

In [2]:
data = data.drop(columns=["observation_id", "session_id", "time_of_day"])

data.head()

,timestamp,location_id,signal_mean,signal_std,rx_link_rate_mean,tx_link_rate_mean,rtt_mean_ms,rtt_std_ms,jitter_ms,packet_loss_pct,throughput_down_mbps
0,2026-09-05T16:15:15,1,79.416667,0.514929,866.7,866.7,1.100000,0.316228,0.222222,0.0,94.402610
1,2026-09-05T16:15:36,1,80.000000,0.000000,866.7,866.7,1.800000,2.529822,0.888889,0.0,94.365150
2,2026-09-05T16:15:57,1,80.000000,0.000000,866.7,866.7,2.666667,4.636809,1.750000,10.0,94.672873
3,2026-09-05T16:16:23,1,80.000000,0.000000,866.7,866.7,1.555556,1.333333,1.125000,10.0,93.968420
4,2026-09-05T16:16:48,1,81.000000,0.000000,866.7,866.7,3.800000,4.732864,4.222222,0.0,94.647882

### 3. Đổi kiểu giá trị biến `timestamp` thành kiểu số, đồng thời đổi tên thành `seconds_since_midnight`
Lý do: Giúp dễ tính toán và khám phá trong EDA

In [3]:
ts_col = pd.to_datetime(data['timestamp'])

data['timestamp'] = ts_col.dt.hour * 3600 + ts_col.dt.minute * 60 + ts_col.dt.second

data.rename(columns={'timestamp': 'seconds_since_midnight'}, inplace=True)

data.head()

,seconds_since_midnight,location_id,signal_mean,signal_std,rx_link_rate_mean,tx_link_rate_mean,rtt_mean_ms,rtt_std_ms,jitter_ms,packet_loss_pct,throughput_down_mbps
0,58515,1,79.416667,0.514929,866.7,866.7,1.100000,0.316228,0.222222,0.0,94.402610
1,58536,1,80.000000,0.000000,866.7,866.7,1.800000,2.529822,0.888889,0.0,94.365150
2,58557,1,80.000000,0.000000,866.7,866.7,2.666667,4.636809,1.750000,10.0,94.672873
3,58583,1,80.000000,0.000000,866.7,866.7,1.555556,1.333333,1.125000,10.0,93.968420
4,58608,1,81.000000,0.000000,866.7,866.7,3.800000,4.732864,4.222222,0.0,94.647882

### 4. Thay giá trị tương ứng các địa điểm thu dữ liệu thành giá trị khoảng cách, đồng thời đổi tên thành `distance_m`

In [4]:
data['location_id'] = data['location_id'].replace({1: 1, 2: 15, 3: 5})
data.rename(columns={'location_id': 'distance_m'}, inplace=True)

data.head()

,seconds_since_midnight,distance_m,signal_mean,signal_std,rx_link_rate_mean,tx_link_rate_mean,rtt_mean_ms,rtt_std_ms,jitter_ms,packet_loss_pct,throughput_down_mbps
0,58515,1,79.416667,0.514929,866.7,866.7,1.100000,0.316228,0.222222,0.0,94.402610
1,58536,1,80.000000,0.000000,866.7,866.7,1.800000,2.529822,0.888889,0.0,94.365150
2,58557,1,80.000000,0.000000,866.7,866.7,2.666667,4.636809,1.750000,10.0,94.672873
3,58583,1,80.000000,0.000000,866.7,866.7,1.555556,1.333333,1.125000,10.0,93.968420
4,58608,1,81.000000,0.000000,866.7,866.7,3.800000,4.732864,4.222222,0.0,94.647882

### 5. Đổi tên cột `signal_mean` và `signal_std` thành lần lượt `signal_mean_pct` và `signal_std_pct`

In [5]:
data.rename(columns={'signal_mean': 'signal_mean_pct', 'signal_std': 'signal_std_pct'}, inplace=True)

data.head()

,seconds_since_midnight,distance_m,signal_mean_pct,signal_std_pct,rx_link_rate_mean,tx_link_rate_mean,rtt_mean_ms,rtt_std_ms,jitter_ms,packet_loss_pct,throughput_down_mbps
0,58515,1,79.416667,0.514929,866.7,866.7,1.100000,0.316228,0.222222,0.0,94.402610
1,58536,1,80.000000,0.000000,866.7,866.7,1.800000,2.529822,0.888889,0.0,94.365150
2,58557,1,80.000000,0.000000,866.7,866.7,2.666667,4.636809,1.750000,10.0,94.672873
3,58583,1,80.000000,0.000000,866.7,866.7,1.555556,1.333333,1.125000,10.0,93.968420
4,58608,1,81.000000,0.000000,866.7,866.7,3.800000,4.732864,4.222222,0.0,94.647882

### 6. Lưu lại dataset đã qua cleaning

In [6]:
try:
    data.to_csv("../data/cleaned/data-cleaned.csv", mode="x", index=False)
    print("File created successfully.")
except FileExistsError:
    print("File already exists.")

File already exists.