# Baseline

### 1. Import thư viện cần thiết và load dataset

In [33]:
import pandas as pd

data_train = pd.read_csv("../data/preprocessed/data_train.csv")
data_test = pd.read_csv("../data/preprocessed/data_test.csv")

display(data_train)
display(data_test)

,distance_m,signal_mean_pct,rx_link_rate_mean,rtt_mean_ms,jitter_ms,packet_loss_pct,throughput_down_mbps
0,5,90.000000,144.4,1.500000,0.777778,0.0,88.205492
1,15,33.250000,1.0,108.888889,55.500000,10.0,0.000000
2,15,34.000000,1.0,290.500000,262.222222,0.0,0.105660
3,1,84.230769,866.7,1.000000,0.000000,0.0,93.401740
4,1,83.000000,866.7,2.111111,2.500000,10.0,94.606291
...,...,...,...,...,...,...,...
283,1,83.000000,866.7,2.500000,2.333333,0.0,92.199988
284,5,89.333333,144.4,3.222222,4.625000,10.0,84.029303
285,5,90.000000,144.4,1.300000,0.444444,0.0,79.932116
286,1,84.615385,866.7,1.000000,0.000000,0.0,92.998248
287,1,84.230769,866.7,1.200000,0.444444,0.0,93.268655

,distance_m,signal_mean_pct,rx_link_rate_mean,rtt_mean_ms,jitter_ms,packet_loss_pct,throughput_down_mbps
0,5,91.000000,144.400000,1.5,1.111111,0.0,90.725926
1,15,41.000000,5.250000,3.1,3.222222,0.0,0.000000
2,5,87.750000,144.400000,1.4,0.777778,0.0,76.034358
3,15,29.000000,1.000000,992.6,882.555556,0.0,0.000000
4,5,84.833333,144.400000,5.8,6.777778,0.0,18.118921
...,...,...,...,...,...,...,...
67,5,89.000000,144.400000,2.4,2.000000,0.0,89.400531
68,15,30.000000,1.000000,158.2,148.444444,0.0,0.000000
69,15,24.250000,1.000000,159.2,211.777778,0.0,0.000000
70,15,49.500000,2.708333,361.4,333.888889,0.0,0.418837
71,5,90.000000,144.400000,2.4,2.111111,0.0,88.175048

### 2. Định nghĩa các biến `FEATURES` và biến `TARGET`

In [34]:
FEATURES = [
    "distance_m",
    "signal_mean_pct",
    "rx_link_rate_mean",
    "rtt_mean_ms",
    "jitter_ms",
    "packet_loss_pct"
]

TARGET = "throughput_down_mbps"

### 3. Tính trung bình biến `TARGET` của tập `data_train`

In [35]:
baseline_mean = data_train[TARGET].mean()

print(f"Training mean throughput: {baseline_mean:.2f} Mbps")

Training mean throughput: 54.91 Mbps

### 4. Sử dụng trung bình trên để dự đoán giá trị biến `TARGET` của tập `data_test`

In [36]:
y_pred_baseline = data_test[[TARGET]]

y_pred_baseline[:] = baseline_mean

display(y_pred_baseline)

    throughput_down_mbps
0              54.913612
1              54.913612
2              54.913612
3              54.913612
4              54.913612
..                   ...
67             54.913612
68             54.913612
69             54.913612
70             54.913612
71             54.913612

[72 rows x 1 columns]

### 5. Lưu lại dự đoán của mô hình baseline

In [37]:
try:
    y_pred_baseline.to_csv("../data/prediction-baseline/prediction_baseline.csv", mode="x", index=False)
    print("File created successfully.")
except FileExistsError:
    print("File already exists.")

File created successfully.